spring.application.name=NotificationServiceV2
spring.datasource.url = jdbc:postgresql://localhost:5432/notification_service
spring.datasource.username=postgres
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update


